name: app_chula
description: "Um player de áudio com controles de pitch e velocidade."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.10.5
  audio_session: 0.2.2

  file_picker: ^10.3.3

  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.0.15
  path: ^1.8.3


  flutter_riverpod: ^3.0.3
  
  cupertino_icons: ^1.0.2
  flutter_platform_widgets: ^9.0.0

  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
